version: '3.9'
services:
  # backend:
  #   build:
  #     dockerfile: ./apps/backend/Dockerfile
  #     target: development
  #     context: .
  #   command: npm run serve:backend
  #   ports:
  #     - "3333:3333"
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_HOST: db
  #     DATABASE_PORT: 8280
  #     DATABASE_USER: falvapp
  #     DATABASE_NAME: falvapp
  #     DATABASE_PASSWORD: keepkalmandpanik
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./docker-postgres-multiple-dbs.sh:/docker-entrypoint-initdb.d/docker-postgres-multiple-dbs.sh
    environment:
      POSTGRES_USER: nxsuperuser
      POSTGRES_PASSWORD: keepkalmandpanik
      POSTGRES_DB_NAMES: falvapp

networks:
  default:
    name: example_dev_network
    driver: bridge